name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-elecrton:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with: 
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
            CYPRESS_RECORD_KEY: 3a21d1fc-56e2-474e-82d9-ca6f691aa401
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
